version: "3.9"

services:
  db:
    image: postgres:15
    container_name: faceid-db-1
    restart: always
    environment:
      POSTGRES_DB: faceid
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: Yoqub0522
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: faceid-backend-1
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      DB_NAME: faceid
      DB_USER: db_user
      DB_PASSWORD: Yoqub0522
      DB_HOST: db
      DB_PORT: 5432

    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: